service: serverless-graphql

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-warmup

custom:
  customDomain:
    domainName: api-gatsby.sidhartha.dev
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
  stage: dev
  region: us-east-1

functions:
  publicAPI:
    handler: src/graphql/public.graphql
    warmup: true
    events:
      - http:
          path: public
          method: post
          cors: true
  graphql:
    handler: src/graphql/server.graphql
    warmup: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src/graphql/public.graphql
    events:
      - http:
          path: public
          method: get
